[setup]
pkgs = ["nodejs_20", "npm_10", "openssl"]

[phases.setup]
nixPkgs = ["nodejs_20", "npm_10", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]
